import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    // ✅ Fixed: removed ./src/ prefix — project uses app/ at root
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#181e00",
        "secondary": "#556500",
        "on-tertiary": "#ffffff",
        "primary-container": "#ff8a65",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-highest": "#e8e2d7",
        "on-primary-fixed-variant": "#7f2a0d",
        "tertiary": "#326578",
        "on-primary-fixed": "#3a0b00",
        "on-surface": "#1d1c15",
        "on-error-container": "#93000a",
        "primary": "#9f4122",
        "surface-container-low": "#f9f3e8",
        "surface-tint": "#9f4122",
        "secondary-fixed": "#d6ed7a",
        "tertiary-container": "#80b1c7",
        "on-surface-variant": "#56423c",
        "surface-bright": "#fff9ee",
        "on-tertiary-fixed": "#001f29",
        "on-secondary-fixed-variant": "#3f4c00",
        "on-tertiary-container": "#074457",
        "outline-variant": "#ddc0b8",
        "surface": "#fff9ee",
        "secondary-container": "#d6ed7a",
        "inverse-primary": "#ffb59e",
        "secondary-fixed-dim": "#bbd062",
        "error": "#ba1a1a",
        "surface-dim": "#dfd9cf",
        "surface-variant": "#e8e2d7",
        "outline": "#89726b",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#bbe9ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f6f0e5",
        "primary-fixed-dim": "#ffb59e",
        "surface-container": "#f3ede2",
        "primary-fixed": "#ffdbd0",
        "on-background": "#1d1c15",
        "on-secondary-container": "#5a6c00",
        "surface-container-high": "#ede8dd",
        "inverse-surface": "#333029",
        "on-primary-container": "#752305",
        "tertiary-fixed-dim": "#9ccee4",
        "on-tertiary-fixed-variant": "#154d5f",
        "surface-container-lowest": "#ffffff",
        "background": "#fff9ee",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "32px",
        "container-padding": "64px",
        "unit": "8px",
        "section-gap": "120px",
        "card-internal": "40px",
      },
      fontFamily: {
        // ✅ Fixed: font-sans now resolves to Plus Jakarta Sans via next/font CSS variable
        "sans": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        // existing named scale utilities (unchanged)
        "body-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "label-caps": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "display-xl": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;